---
- name: Deploy log monitoring script
  hosts: all
  tasks:
    - name: TEST ONLY - Create script with inline content
      copy:
        content: |
          #!/bin/bash
          echo "Hello, World!"
        dest: /tech/admin/monitoring/incompleteCertChainMonitor/xxx.sh
        mode: '0755'
